import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
    children: React.ReactNode
  }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex justify-evenly py-4 w-full px-5'> 
          <Link href="/">Home</Link>
          <Link href="/sign-up">Sign Up</Link>
          <Link href="/login">Login</Link>
          <Link href="/create-post">Create Post</Link>
          <Link href="/posts">Posts</Link>
        </div>
        {children}</body>
    </html>
  )
}
